export {
  addDays,
  calculatePanelLayout,
  calculateQuotation,
  formatQuoteDateKey,
  formatThaiDate,
  formatThaiMoney,
  generateQuotationNumber,
  getPanelSpec,
  getQuotationService,
  normalizeDiscountPercent,
  normalizeQuoteQuantity,
  normalizeTargetKwp,
  parseKwpValue,
  quotationPricingRules,
  reserveLocalQuotationNumber,
  roundEngineering,
  roundMoney,
  type PanelLayout,
  type PanelSpec,
  type PricingRules,
  type PricingService,
  type QuotationLine,
  type QuotationLineInput,
  type QuotationTotals,
  type StorageLike,
} from "@shared/quotation";
