CREATE TABLE `quotations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadId` int,
	`quoteNumber` varchar(64) NOT NULL,
	`quotationStatus` enum('draft','issued','sent','accepted','expired') NOT NULL DEFAULT 'issued',
	`sourceAction` varchar(32) DEFAULT 'preview',
	`customerName` varchar(255) NOT NULL,
	`customerCompany` varchar(255),
	`customerEmail` varchar(320),
	`customerPhone` varchar(32),
	`customerLineId` varchar(100),
	`customerAddress` text,
	`customerNote` text,
	`lineItems` text NOT NULL,
	`totals` text NOT NULL,
	`systemDesign` text,
	`primaryPanelModel` varchar(255),
	`primaryPanelWatts` int,
	`subtotal` int NOT NULL DEFAULT 0,
	`discount` int NOT NULL DEFAULT 0,
	`vat` int NOT NULL DEFAULT 0,
	`grandTotal` int NOT NULL DEFAULT 0,
	`issuedAt` timestamp NOT NULL DEFAULT (now()),
	`validUntil` timestamp,
	`ipAddress` varchar(45),
	`userAgent` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `quotations_id` PRIMARY KEY(`id`),
	CONSTRAINT `quotations_quoteNumber_unique` UNIQUE(`quoteNumber`)
);
